Refactoring
majkah0/nos-lp-foundations-workspace pull request #4
Opened 2023-08-22 17:27 UTC by majkah0

2023-08-23 16:19 UTC, nunohelibeires requested changes

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +    parser.add_argument("region", help = 'Input region argument.', type = str)
```suggestion
    parser.add_argument("--region", help = 'Input region argument.', type = str)
```
I was not able to make it work like this, still I think that when the argument is an action it should be a flag, like `--region` or `-r`. That way I'm not getting the error in the cmd line.

(nice-to-have: default value)

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +    save_data(region_life_expectancy_data, region)
you could encapsulate these 3 lines into one `main()` function.

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +    path = Path().cwd() / 'life_expectancy' / 'data' / 'eu_life_expectancy_raw.tsv'
```suggestion
    path = './data/eu_life_expectancy_raw.tsv'
```
We should always use relative paths (hardcoded paths are a pain when sharing code with other developers) and even the path could be an optional function variable where you could have a global variable with the prefix path in case you need it.

Suggestions:
```
BASE_DIR = Path().cwd() / 'life_expectancy' / 'data'

def load_data(path: Optional[Path] = None) -> pd.DataFrame:
    if path is None:
        path = BASE_DIR / 'eu_life_expectancy_raw.tsv'
    return pd.read_csv(path, sep='\t')
```

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +def export_region_data(df: pd.DataFrame, region: str) -> None:
```suggestion
def filter_region_data(df: pd.DataFrame, region: str) -> pd.DataFrame:
```
The function is returning a dataframe but type hint indicates None.

Also, in this function we are not exporting data but only filtering or slicing the dataframe so we could be more explicit in the function name. Smth like filter_region_data or slice_region_dataframe

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +def clean_data(df: pd.DataFrame, region: str = 'PT') -> None:
```suggestion
def clean_data(df: pd.DataFrame, region: str = 'PT') -> pd:DataFrame:
```
Same as before.

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +    path = Path().cwd() / 'life_expectancy' / 'data' / file_name
Same as the `load_data()` function, we should use relative paths.
Here we could make use of the BASE_DIR variable again.

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
> +def extract_flag(df: pd.DataFrame) -> pd.DataFrame:
What is the aim of this `flag` column?

2023-08-23 16:19 UTC, nunohelibeires commented on README.md
(nice to have) would be to have some example commands, like an `HOW TO` paragraph

2023-08-23 16:19 UTC, nunohelibeires commented on life_expectancy/cleaning.py
Nice work @majkah0!
There are a few things that could improve your code overall that I will pin point during this review.
Things that you'll pick up with time and a lot of code read from other developers :)

1. Some functions are missing their docstrings. (and the ones that have should also include input arguments and returned variables)
2. It would be a nice thing to have a intro description in the header of the module file, like:
`"""Module for cleaning life expectancy data."""`

2023-08-23 16:22 UTC, nunohelibeires commented
You should also add the CI/CD to his branch in order to keep track of this to improve in your code before merging.

Linting errors:

> ************* Module life_expectancy.cleaning
life_expectancy/cleaning.py:77:0: C0304: Final newline missing (missing-final-newline)
life_expectancy/cleaning.py:10:23: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:17:36: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:22:12: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:31:17: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:37:23: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:45:23: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:45:41: W0621: Redefining name 'region' from outer scope (line 74) (redefined-outer-name)
life_expectancy/cleaning.py:51:15: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:51:33: W0621: Redefining name 'region' from outer scope (line 74) (redefined-outer-name)
life_expectancy/cleaning.py:65:14: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
life_expectancy/cleaning.py:65:32: W0621: Redefining name 'region' from outer scope (line 74) (redefined-outer-name)
life_expectancy/cleaning.py:2:0: C0411: standard import "import argparse" should be placed before "import pandas as pd" (wrong-import-order)
life_expectancy/cleaning.py:3:0: C0411: standard import "from pathlib import Path" should be placed before "import pandas as pd" (wrong-import-order)

------------------------------------------------------------------
Your code has been rated at 8.08/10 (previous run: 8.08/10, +0.00)

2023-08-30 14:34 UTC, majkah0 commented on life_expectancy/cleaning.py
> +    parser.add_argument("region", help = 'Input region argument.', type = str)
I corrected the flag syntax and added a default value.

2023-08-30 14:38 UTC, majkah0 commented on life_expectancy/cleaning.py
> +    save_data(region_life_expectancy_data, region)
I created a main function for this.

2023-08-30 14:52 UTC, majkah0 commented on life_expectancy/cleaning.py
> +    path = Path().cwd() / 'life_expectancy' / 'data' / 'eu_life_expectancy_raw.tsv'
I changed this according to your suggestion.

2023-08-30 15:07 UTC, majkah0 commented on life_expectancy/cleaning.py
> +def export_region_data(df: pd.DataFrame, region: str) -> None:
I changed the function name to filter_region_data and corrected the type hint.

2023-08-30 15:22 UTC, majkah0 commented on life_expectancy/cleaning.py
> +    path = Path().cwd() / 'life_expectancy' / 'data' / file_name
I corrected the function with a relative path.

2023-08-30 15:24 UTC, majkah0 commented on life_expectancy/cleaning.py
> +def extract_flag(df: pd.DataFrame) -> pd.DataFrame:
The flag has a meaning in the original dataset and might be interesting during further analysis of this dataset, but it is irrelevant for the task that was asked for, so I should probably remove it.

2023-08-30 15:31 UTC, majkah0 commented
The CI/CD runs on this branch, I just did not pay attention to the linting output :) I will check it out.

2023-08-30 16:16 UTC, majkah0 commented on life_expectancy/cleaning.py
Thank you Nuno!
I made better docstrings for functions and the module.

2023-08-30 16:17 UTC, majkah0 commented on README.md
I will add this in a separate commit later.

2023-09-05 21:10 UTC, majkah0 commented on README.md
I added a readme (shamelessly copied and modified from Sofia).

2023-09-15 09:46 UTC, closed without merging